I, [2016-12-08T17:33:34.709704 #7750]  INFO -- : Started POST "/bot" for 173.252.90.125 at 2016-12-08 17:33:34 +0100
F, [2016-12-08T17:33:34.756519 #7750] FATAL -- : 
ActiveRecord::StatementInvalid (Could not find table 'users'):
  lib/bot/base_bot_logic.rb:166:in `handle_user'
  lib/bot/base_bot_logic.rb:194:in `handle_request'
  app/bots/main.rb:11:in `block in <top (required)>'


I, [2016-12-08T17:36:56.477213 #7780]  INFO -- : Started GET "/" for ::1 at 2016-12-08 17:36:56 +0100
F, [2016-12-08T17:36:56.532872 #7780] FATAL -- : 
ActionController::RoutingError (No route matches [GET] "/"):
  actionpack (4.2.6) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.6) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.6) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.6) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.6) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.6) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.6) lib/rails/engine.rb:518:in `call'
  railties (4.2.6) lib/rails/application.rb:165:in `call'
  rack (1.6.4) lib/rack/content_length.rb:15:in `call'
  puma (3.4.0) lib/puma/configuration.rb:224:in `call'
  puma (3.4.0) lib/puma/server.rb:569:in `handle_request'
  puma (3.4.0) lib/puma/server.rb:406:in `process_client'
  puma (3.4.0) lib/puma/server.rb:271:in `block in run'
  puma (3.4.0) lib/puma/thread_pool.rb:114:in `call'
  puma (3.4.0) lib/puma/thread_pool.rb:114:in `block in spawn_thread'


I, [2016-12-08T17:37:28.614469 #7780]  INFO -- : Started POST "/bot" for 173.252.90.104 at 2016-12-08 17:37:28 +0100
F, [2016-12-08T17:37:28.647711 #7780] FATAL -- : 
ActiveRecord::StatementInvalid (Could not find table 'users'):
  lib/bot/base_bot_logic.rb:166:in `handle_user'
  lib/bot/base_bot_logic.rb:194:in `handle_request'
  app/bots/main.rb:11:in `block in <top (required)>'


